Documentation:
   Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
Rails/Blank:
  Description: 'Enforce using `blank?` and `present?`.'
  Enabled: false
  # Convert checks for `nil` or `empty?` to `blank?`
  NilOrEmpty: true
  # Convert usages of not `present?` to `blank?`
  NotPresent: false
  # Convert usages of `unless` `present?` to `if` `blank?`
  UnlessPresent: false
