Documentation:
   Enabled: false
LineLength:
   Max: 99
BlockLength:
   Max: 99
Rails/Blank:
  Description: 'Enforce using `blank?` and `present?`.'
  Enabled: false
  # Convert checks for `nil` or `empty?` to `blank?`
  NilOrEmpty: true
  # Convert usages of not `present?` to `blank?`
  NotPresent: false
  # Convert usages of `unless` `present?` to `if` `blank?`
  UnlessPresent: false
